allan_node:
  ros__parameters:
    topic: /edie/sensor/offset_imu
    bag_path: /home/higony/ros2_ws/src/edie9/edie_localization/third_party/viso_inertial_calib/data/imu_static_2h
    msg_type: ros
    publish_rate: 382
    sample_rate: 382
